### PR TITLE
Fuzzing (WIP)

### PR DESCRIPTION
**Pull request by 256dpi**
I added a basic fuzzing test with https://github.com/dvyukov/go-fuzz.

Bugs found so far:
- [x] Unset `RemainingLength` when encoding a Disconnect message.
- [ ] Slice bounds out of range: `header.go:224`
- [ ] Slice bounds out of range: `publish.go:173`
- [ ] Index out of range: `connect.go:488`
- [ ] Index out of range: `connack.go:98`
- [ ] Slice bounds out of range: `suback.go:98`
- [ ] Index out of range: `subscribe.go:177`

Goal is to run the fuzzing test for min. 2 hours without any errors.

### CODE REVIEW

**Comment by 256dpi** [comment]
@zhenjl: I just started the fuzzing. There are already some bugs related to not checking properly if the buffers are big enough before reading. Do you see a quick general fix, or should we check before each extraction the size of the buffer?

**Comment by zhenjl** [comment]
Let me take a look later tonight to see if there's a quick general fix.

**Comment by zhenjl** [comment]
No easy fix...will be going through the list this wkend. Anymore fuzz bugs identified?

**Comment by 256dpi** [comment]
Nah, I guess we have to check the length of the buffer before every access. I wonder if this could be abstracted a little bit, like:

```go
slice, err := buf.take(2)
```

Otherwise we end up with a lot of:

```go
if len(buf) < offset + 2 {
  return fmt.Errorf("buffer to short...")
}
```

Or what do you think would be the proper go way?

**Comment by 256dpi** [comment]
I stopped the fuzzing as we first need to fix all unsafe slice and array access. If the code is stable I will run the fuzzing on a EC2 instance for a day or so to be 100% sure. In the meantime you can also run the test on your own (https://github.com/gomqtt/message/blob/fuzzing/message.go#L393) to find more crashes.

Do you wanna look into fixing the array/slice problem, or should I work on that?

**Comment by 256dpi** [comment]
Just stumbled across:
http://stackoverflow.com/questions/13660864/reading-specific-number-of-bytes-from-a-buffered-reader-in-golang

Is there a reason that you decided to operate on raw []byte slices rather than a Reader in Decode and a Writer in Encode? (I didn't work a lot with binary stuff in go yet, so I haven't made up my mind on what is better...)

**Comment by zhenjl** [comment]
Purely for performance reasons. Any interface use shaves off some performance.

**Comment by zhenjl** [comment]
Btw, as much as I want to tackle some of these, my time's just not agreeing with me, especially w/ VMworld this week. So you should feel free to work on these as you see fit. Thx...

**Comment by 256dpi** [comment]
Closed as #6 will fix all bugs.

**Pull request closed without merging**
